version: '3.4'

services:
  event-store:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      POSTGRES_DB: events

  tests:
    build: .
    depends_on:
      - event-store
